name: redis-desktop-manager
version: 2020
version-script: cat $SNAPCRAFT_STAGE/version
summary: Redis Desktop Manager
description: Cross-platform GUI management tool for Redis

grade: stable
confinement: strict

plugs:
  dot-rdm:       
    interface: personal-files
    read:
     - $HOME/.rdm

apps:
  rdm:
    command: desktop-launch $SNAP/opt/redis-desktop-manager/rdm --settings-dir $SNAP_USER_COMMON
    desktop: usr/share/applications/rdm.desktop
    plugs: 
     - home
     - unity7
     - opengl
     - gsettings
     - network
     - network-bind
     - x11
     - desktop
     - desktop-legacy
     - ssh-keys     
     - dot-rdm      
    environment:
      DISABLE_WAYLAND: 1
      WAYLAND_DISPLAY: no-display
      QTCOMPOSE: $SNAP/usr/share/X11/locale     
parts:
  application:
    plugin: qmake-rdm
    source: https://github.com/uglide/RedisDesktopManager.git
    source-branch: '2020'
    after: [qt, desktop-gtk3, gcc7, botan]
    build-packages:
     - python3
     - git
     - virtualenv
     - wget
     - unzip
    source-subdir: src
    project-files: 
     - rdm.pro
    qmake-binary: $SNAPCRAFT_STAGE/opt/qt5/bin/qmake
    options:
     - VERSION="$(git describe --abbrev=0 --tags)+$(git rev-parse --short HEAD)"
    override-build: |
      cd ../src
      bash -c 'pushd ./3rdparty/qredisclient && wget -O deps.zip "https://docs.google.com/uc?export=download&id=1h6Q-soYk1byAupwD10Vvr3GqZsr2V29m" && unzip -o deps.zip && popd'
      bash -c 'pushd ./src && $SNAPCRAFT_STAGE/opt/qt5/bin/lrelease rdm.pro && popd'
      sed -i "s|^Icon=.*|Icon=\${SNAP}/usr/share/pixmaps/rdm.png|g" src/resources/rdm.desktop
      export RDM_VERSION="$(git describe --abbrev=0 --tags)+$(git rev-parse --short HEAD)"
      echo "App version: $RDM_VERSION"
      echo $RDM_VERSION > $SNAPCRAFT_STAGE/version      
      cd ../build
      snapcraftctl build
      mkdir -p ../install/opt/redis-desktop-manager/lib/plugins
      cp -R $SNAPCRAFT_STAGE/opt/qt5/qml ../install/opt/redis-desktop-manager/lib/plugins
  botan:
    plugin: make
    build-packages:
      - python
    source: https://github.com/randombit/botan.git
    override-build: |
      export CC=gcc-5
      export CXX=g++-5
      python configure.py --prefix=/usr
      snapcraftctl build
  formatters:    
    source: . 
    plugin: python
    python-version: python3
    requirements: $SNAPCRAFT_PART_SRC/../../application/src/src/py/requirements.txt
  qt:
    plugin: qtbuilder
    qt-version: 5.13.2
    qt-source-git: https://code.qt.io/qt/qt5.git
    qt-submodules:
      - qtbase
      - qtimageformats
      - qtcharts
      - qtdeclarative
      - qtquickcontrols
      - qtquickcontrols2
      - qtsvg
      - qttools
    environment:
      - CC: gcc-7
      - CXX: g++-7
      - QMAKE_CC: gcc-7
      - QMAKE_CXX: g++-7
    build-packages:
      - libdbusmenu-glib-dev
      - libffi-dev
      - liblzma-dev
      - libssl-dev
      - libx11-xcb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-sync-dev
      - libxcb-util0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxrender-dev
      - libfontconfig1-dev
      - cmake
    configflags:
      - -prefix
      - $SNAPCRAFT_STAGE/opt/qt5
      - -release
      - -force-debug-info
      - -opensource
      - -confirm-license
      - -system-freetype
      - -qt-zlib
      - -qt-libpng
      - -qt-libjpeg
      - -qt-harfbuzz
      - -qt-pcre
      - -qt-xcb
      - -xkbcommon
      - -no-opengl
      - -fontconfig
      - -static
      - -dbus-runtime
      - -openssl-linked      
      - -nomake
      - examples
      - -nomake
      - tests
    after:
      - libxkbcommon
    prime: [-./*]
  libxkbcommon:
    source: https://github.com/xkbcommon/libxkbcommon.git
    source-depth: 1
    source-tag: xkbcommon-0.8.4
    plugin: autotools
    build-packages:
      - xutils-dev
      - bison
      - python-xcbgen
    configflags:
      - --disable-x11
    prime: [-./*]
  gcc7:
    plugin: nil
    build-packages:
      - libmpc-dev
      - libcloog-ppl-dev
    override-pull: |
      echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" | \
            sudo tee /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 60C317803A41BA51845E371A1E9377A2BA9EF27F
      sudo apt-get update \
        -o Dir::Etc::sourcelist="sources.list.d/ubuntu-toolchain-r.list" \
        -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
      snapcraftctl pull
    override-build: |
      sudo apt install gcc-7 g++-7 -o Debug::pkgProblemResolver=yes --no-install-recommends -y
      sudo apt-mark auto gcc-7 g++-7
      sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                         --slave /usr/bin/g++ g++ /usr/bin/g++-7 
      sudo update-alternatives --config gcc
      gcc --version
      g++ --version
      snapcraftctl build
    prime: [-./*]
