name: redis-desktop-manager
adopt-info: application
summary: RESP.app - GUI for Redis ® (formerly RedisDesktopManager)
description: Cross-platform GUI management tool for Redis

base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

assumes:
- snapd2.37

plugs:
  dot-rdm:       
    interface: personal-files
    read:
     - $HOME/.rdm
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
apps:
  resp:
    command: bin/desktop-launch $SNAP/opt/resp_app/resp --settings-dir $SNAP_USER_COMMON
    desktop: usr/share/applications/resp.desktop
    plugs: 
     - home
     - unity7
     - opengl
     - gsettings
     - network
     - network-bind
     - x11
     - desktop
     - desktop-legacy
     - ssh-keys     
     - dot-rdm
     - wayland
    extensions:
     - gnome-3-38
parts:
  application:
    plugin: make
    source: https://github.com/uglide/RedisDesktopManager.git
    source-branch: '2022'
    after: [qt, botan, desktop-qt5]
    build-packages:
     - python3
     - python3-dev
     - git
     - virtualenv
     - wget
     - unzip
     - cmake
     - liblz4-dev
     - libzstd-dev
     - libbrotli-dev
     - libsnappy-dev
    stage-packages:
     - libxcb-icccm4
     - libxcb-image0
     - libxcb-keysyms1
     - libxcb-randr0
     - libxcb-render-util0
     - libxcb-shape0
     - libxcb-util1
     - libxcb-xinerama0
     - libxcb-xkb1
     - libxkbcommon-x11-0
     - libfontconfig1
     - ibus
     - liblz4-1
     - libzstd1
     - libbrotli1
     - libsnappy1v5
    source-subdir: src
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      - PATH: $SNAPCRAFT_STAGE/usr/lib/qt5/bin:$PATH
    override-build: |
      cd ../src
      bash -c 'pushd ./src && lrelease resp.pro && popd'
      export APP_VERSION="$(git describe --abbrev=0 --tags)+$(git rev-parse --short HEAD)"
      echo "App version: $APP_VERSION"
      snapcraftctl set-version "$APP_VERSION"
      cd ../build
      sed -i "s|^Icon=.*|Icon=\${SNAP}/usr/share/pixmaps/resp.png|g" src/resources/resp.desktop
      bash -c 'pushd ./3rdparty/qredisclient && wget -O deps.zip "https://rdm-dev.nyc3.digitaloceanspaces.com/snap/deps.zip?v3" && unzip -o deps.zip && cp $SNAPCRAFT_STAGE/usr/lib/libbotan-2.a . && popd'
      bash -c 'pushd ./src && qmake resp.pro VERSION="$APP_VERSION" "SYSTEM_LZ4=1" "SYSTEM_ZSTD=1" "SYSTEM_SNAPPY=1" "SYSTEM_BROTLI=1" && make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT && make install INSTALL_ROOT=${SNAPCRAFT_PART_INSTALL} && popd'
  botan:
    plugin: make
    build-packages:
      - python
    source: https://github.com/randombit/botan.git
    source-commit: 3ed6eaa3c1236aed844f5475e2df8b89b3286ac4
    override-build: |
      python configure.py --prefix=/usr
      snapcraftctl build
    prime:
      - -./usr/include
      - -./usr/bin
      - -./usr/lib/*.a
  formatters:    
    source: . 
    plugin: nil
    build-packages:
      - python3.8
      - python3-pip
    override-build: |
      python3 -m pip install -U bitstring cbor msgpack git+https://github.com/mrnom/phpserialize.git#egg=phpserialize rdbtools python-lzf numpy pandas --target=$SNAPCRAFT_PART_INSTALL/opt/redis-desktop-manager/
  qt:   
    plugin: nil
    override-pull: |
      QT=5_15_2
      git clone -b v5.15.2 --depth=1 git://code.qt.io/qt/qt5.git .
      perl init-repository --module-subset=qtbase,qtwayland,qtimageformats,qtxmlpatterns,qtcharts,qtdeclarative,qtquickcontrols,\
      qtquickcontrols2,qtgraphicaleffects,qtsvg,qttools
      git submodule update qtbase qtwayland qtimageformats qtxmlpatterns qtcharts \
      	qtdeclarative qtquickcontrols qtquickcontrols2 qtgraphicaleffects qtsvg qttools      
    build-packages:
      - libegl-dev
      - libgl-dev  
      - libdbusmenu-glib-dev
      - libffi-dev
      - liblzma-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libssl-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-xinput-dev
      - libxcb-xkb-dev
      - libxcb-sync0-dev
      - libxcursor-dev
      - libxrender-dev
      - libxi-dev
      - libxext-dev
      - libxfixes-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libwayland-dev  
      - cmake
    stage-packages:
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libgl1
      - libglib2.0-0
      - libgtk-3-0
      - libicu66
      - libpcre2-16-0
      - libpng16-16
      - libssl1.1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1  
      - zlib1g  
    override-build: |
      ./configure \
       -prefix /usr \
       -bindir /usr/lib/qt5/bin \
       -libdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET \
       -docdir /usr/share/qt5/doc \
       -headerdir /usr/include/$SNAPCRAFT_ARCH_TRIPLET/qt5 \
       -datadir /usr/share/qt5 \
       -archdatadir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5 \
       -plugindir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins \
       -importdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/imports \
       -translationdir /usr/share/qt5/translations \
       -hostdatadir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5 \
       -sysconfdir /etc/xdg \
       -examplesdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/examples \
       -release \
       -force-debug-info \
       -opensource \
       -confirm-license \
       -system-freetype \
       -qt-zlib \
       -qt-libpng \
       -qt-libjpeg \
       -qt-harfbuzz \
       -qt-pcre \
       -xcb \
       -xcb-xlib \
       -feature-thread \
       -feature-xkbcommon \
       -bundled-xcb-xinput \
       -no-feature-xcb-sm \
       -no-feature-xcomposite-egl \
       -no-feature-xcomposite-glx \
       -no-feature-wayland-server \
       -fontconfig \
       -dbus-runtime \
       -openssl-linked \
       -nomake examples \
       -nomake tests
       
       make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
       make INSTALL_ROOT="$SNAPCRAFT_PART_INSTALL" install
    prime:
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/mkspecs
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/qmltooling
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/sqldrivers
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/designer
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5Designer*
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5DesignerComponents*
      - -./usr/lib/qt5
      - -./usr/lib/*.a
      - -./usr/share
  desktop-qt5:
    source: https://github.com/desktop-app/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs    
    after:
      - qt
