name: redis-desktop-manager
adopt-info: application
summary: Redis Desktop Manager
description: Cross-platform GUI management tool for Redis
base: core18

grade: stable
confinement: strict

architectures:
  - build-on: amd64

plugs:
  dot-rdm:       
    interface: personal-files
    read:
     - $HOME/.rdm

apps:
  rdm:
    command: desktop-launch $SNAP/opt/redis-desktop-manager/rdm --settings-dir $SNAP_USER_COMMON
    desktop: usr/share/applications/rdm.desktop
    plugs: 
     - home
     - unity7
     - opengl
     - gsettings
     - network
     - network-bind
     - x11
     - desktop
     - desktop-legacy
     - ssh-keys     
     - dot-rdm      
    extensions:
     - gnome-3-28   
    environment:
      DISABLE_WAYLAND: 1
      WAYLAND_DISPLAY: no-display
      QTCOMPOSE: $SNAP/usr/share/X11/locale     
parts:
  application:
    plugin: rdm
    source: https://github.com/uglide/RedisDesktopManager.git
    source-branch: '2020'
    after: [qt, botan]
    build-packages:
     - python3
     - git
     - virtualenv
     - wget
     - unzip
    source-subdir: src
    project-files: 
     - rdm.pro
    qmake-binary: $SNAPCRAFT_STAGE/opt/qt5/bin/qmake
    override-build: |
      cd ../src
      bash -c 'pushd ./3rdparty/qredisclient && wget -O deps.zip "https://docs.google.com/uc?export=download&id=1mcROyZCpno9AMujMHhjqW9whMFbSay7w" && unzip -o deps.zip && popd'
      bash -c 'pushd ./src && $SNAPCRAFT_STAGE/opt/qt5/bin/lrelease rdm.pro && popd'
      sed -i "s|^Icon=.*|Icon=\${SNAP}/usr/share/pixmaps/rdm.png|g" src/resources/rdm.desktop
      export RDM_VERSION="$(git describe --abbrev=0 --tags)+$(git rev-parse --short HEAD)"
      echo "App version: $RDM_VERSION"
      snapcraftctl set-version "$RDM_VERSION"
      sed -i "s/2020\.[[:digit:]]\.0\-dev/$RDM_VERSION/g" ./src/rdm.pro       
      cd ../build
      snapcraftctl build
      mkdir -p ../install/opt/redis-desktop-manager/lib/plugins
      cp -R $SNAPCRAFT_STAGE/opt/qt5/qml ../install/opt/redis-desktop-manager/lib/plugins
  botan:
    plugin: make
    build-packages:
      - python
    source: https://github.com/randombit/botan.git
    source-commit: 9fc0ad1e4ecc3725ee654ea51c9ee6bfae1537f8
    override-build: |
      python configure.py --prefix=/usr
      snapcraftctl build
  formatters:    
    source: . 
    plugin: python
    python-version: python3
    python-packages: 
      - bitstring
      - cbor
      - msgpack
      - git+https://github.com/mrnom/phpserialize.git#egg=phpserialize
      - rdbtools
      - python-lzf
      - numpy
      - pandas
  qt:   
    plugin: qtbuilder
    qt-version: 5.13.2
    qt-source-git: https://code.qt.io/qt/qt5.git
    source: .
    qt-submodules:
      - qtbase
      - qtimageformats
      - qtxmlpatterns
      - qtcharts
      - qtdeclarative
      - qtquickcontrols
      - qtquickcontrols2
      - qtgraphicaleffects
      - qtsvg
      - qttools
    build-packages:
      - libdbusmenu-glib-dev
      - libffi-dev
      - liblzma-dev
      - libssl-dev
      - libx11-xcb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-sync-dev
      - libxcb-util0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxrender-dev
      - libfontconfig1-dev
      - cmake
    configflags:
      - -prefix
      - $SNAPCRAFT_STAGE/opt/qt5
      - -release
      - -force-debug-info
      - -opensource
      - -confirm-license
      - -system-freetype
      - -qt-zlib
      - -qt-libpng
      - -qt-libjpeg
      - -qt-harfbuzz
      - -qt-pcre
      - -qt-xcb
      - -xkbcommon
      - -no-opengl
      - -fontconfig
      - -static
      - -dbus-runtime
      - -openssl-linked      
      - -nomake
      - examples
      - -nomake
      - tests
    after:
      - libxkbcommon
    prime: [-./*]
  libxkbcommon:
    source: https://github.com/xkbcommon/libxkbcommon.git
    source-depth: 1
    source-tag: xkbcommon-0.8.4
    plugin: autotools
    build-packages:
      - xutils-dev
      - bison
      - python-xcbgen
    configflags:
      - --disable-x11
    prime: [-./*]
